{-# LANGUAGE OverloadedStrings #-}

-- | The generated workflow.
module HaskellGha.Workflow
  ( -- * Workflow
    generate
  , workflow
  , renderWorkflow
  ) where

import Data.Foldable
import Data.List qualified as L
import Data.Text qualified as T
import Distribution.Pretty
import Distribution.Version
import System.FilePath

import HaskellGha.Check
import HaskellGha.Config
import HaskellGha.Ghc
import HaskellGha.Options
import HaskellGha.Project
import HaskellGha.Yaml

-- | Read the configuration and the project, and make the workflow. The
-- phases run in order, and each phase shows all its errors.
generate :: Options -> IO (Either [String] Node)
generate opts =
  readConfig opts.config >>= \case
    Left errors -> pure $ Left errors
    Right config ->
      readProject opts.projectDir >>= \case
        Left errors -> pure $ Left errors
        Right project -> pure $ workflow opts config project

-- | Render the workflow with its header comment.
renderWorkflow
  :: String
  -- ^ The version of the tool.
  -> Options
  -> Node
  -> T.Text
renderWorkflow version opts =
  renderYaml
    [ "This file is generated by haskell-gha " <> T.pack version <> ". Do not edit it."
    , "To make it again, run:"
    , "  " <> T.pack (unwords $ commandLine opts)
    ]

-- | Make the workflow.
workflow :: Options -> Config -> Project -> Either [String] Node
workflow opts config project = runCheck $ checks *> pure root
  where
    entries :: [GhcEntry]
    entries = map (.ghc) project.matrix

    checks :: Check ()
    checks =
      traverse_ checkGhcValue (matrixGhcValues config)

    checkGhcValue :: T.Text -> Check ()
    checkGhcValue value
      | value `elem` map entryText entries = pure ()
      | otherwise =
          failure $
            "The matrix of the configuration refers to GHC "
              ++ T.unpack value
              ++ ", but the ghc axis contains only "
              ++ L.intercalate ", " (map (T.unpack . entryText) entries)
              ++ "."

    root :: Node
    root =
      Mapping
        ( topLevel
            [ ("name", config.name)
            , ("on", triggers)
            , ("concurrency", mapping [("group", plain "${{ github.workflow }}-${{ github.ref }}"), ("cancel-in-progress", plain "true")])
            , ("defaults", mapping [("run", mapping $ ("shell", plain "bash") : workingDirectory)])
            , ("jobs", mapping [("build", job)])
            ]
        )
        []

    topLevel :: [(T.Text, Node)] -> [Item (Key, Node)]
    topLevel = zipWith (\i (k, v) -> Item [EmptyLine | i > (0 :: Int)] (Key Plain k, v)) [0 ..]

    triggers :: Node
    triggers =
      mapping
        [ ("push", mapping [("branches", Sequence (map item config.branches) [])])
        , ("pull_request", plain "")
        , ("workflow_dispatch", plain "")
        ]

    workingDirectory :: [(T.Text, Node)]
    workingDirectory = [("working-directory", plain (T.pack projectDir)) | projectDir /= "."]

    projectDir :: FilePath
    projectDir = dropTrailingPathSeparator (normalise opts.projectDir)

    job :: Node
    job =
      Mapping
        ( map item $
            [ (Key Plain "name", jobName)
            , (Key Plain "runs-on", config.runsOn)
            ]
              ++ [(Key Plain "services", s) | Just s <- [config.services]]
              ++ [ (Key Plain "strategy", mapping [("fail-fast", plain "false"), ("matrix", matrix)])
                 , (Key Plain "steps", Sequence (separate steps) [])
                 ]
        )
        []

    jobName :: Node
    jobName = case matrixAxes config of
      [] -> plain "GHC ${{ matrix.ghc }}"
      axes -> singleQuoted . T.intercalate ", " $ "GHC ${{ matrix.ghc }}" : [a <> " ${{ matrix." <> a <> " }}" | a <- axes]

    matrix :: Node
    matrix =
      Mapping
        (item (Key Plain "ghc", sequenceOf (map (singleQuoted . entryText) entries)) : config.matrix)
        []

    -- An empty line before each step except the first.
    separate :: [Item Node] -> [Item Node]
    separate = zipWith (\i s -> if i > (0 :: Int) then s {comments = EmptyLine : s.comments} else s) [0 ..]

    steps :: [Item Node]
    steps =
      concat
        [ [item $ mapping [("uses", plain "actions/checkout@v7")]]
        , [item $ runStep "Install the system packages" Nothing (aptScript config.apt) | not (null config.apt)]
        , [item setupStep]
        , [item $ runStep "Show the versions" Nothing showVersions]
        , [item $ runStep "Configure the project" Nothing configureScript]
        , [ item $ runStep "Enable parallel module builds for the local packages" (Just group) (parallelScript pkgs)
          | (group, pkgs) <- parallelGroups
          ]
        , [ item $ runStep "Enable the GHC job semaphore" (Just semaphoreEntries) "echo 'semaphore: True' >> cabal.project.local\n"
          | not (null semaphoreEntries)
          ]
        , [item $ runStep "Make the build plan" Nothing "cabal build all --dry-run\n"]
        , [item cacheRestore]
        , [item $ runStep "Build the dependencies" Nothing "cabal build all --only-dependencies\n"]
        , [item cacheSave]
        , config.hooks.beforeBuild
        , [item $ runStep "Build" Nothing "cabal build all\n"]
        , config.hooks.afterBuild
        , [ item $ runStep "Run the tests" (Just testEntries) "cabal test all --test-show-details=direct\n"
          | config.tests
          , not (null testEntries)
          ]
        ]

    -- A step with a script. The script runs for the given matrix entries,
    -- or for all of them.
    runStep :: T.Text -> Maybe [GhcEntry] -> T.Text -> Node
    runStep name only script =
      mapping $
        [("name", plain name)]
          ++ [("if", plain (condition es)) | Just es <- [only], es /= entries]
          ++ [("run", literal script)]

    condition :: [GhcEntry] -> T.Text
    condition es =
      "contains(fromJSON('[" <> T.intercalate "," ["\"" <> entryText e <> "\"" | e <- es] <> "]'), matrix.ghc)"

    setupStep :: Node
    setupStep =
      mapping
        [ ("uses", plain "haskell-actions/setup@v2")
        , ("id", plain "setup")
        ,
          ( "with"
          , mapping
              [ ("ghc-version", plain "${{ matrix.ghc }}")
              , ("cabal-version", singleQuoted cabalVersion)
              ]
          )
        ]

    cabalVersion :: T.Text
    cabalVersion = case config.cabalVersion of
      CabalLatest -> "latest"
      CabalVersion v -> T.pack (prettyShow v)

    showVersions :: T.Text
    showVersions =
      T.unlines
        [ "ghc --version"
        , "cabal --version"
        , "echo \"GHC ${{ steps.setup.outputs.ghc-version }}, cabal ${{ steps.setup.outputs.cabal-version }}\" >> \"$GITHUB_STEP_SUMMARY\""
        ]

    configureScript :: T.Text
    configureScript =
      heredoc $
        concat
          [ ["jobs: " <> tshow config.jobs]
          , ["tests: True" | config.tests]
          , ["benchmarks: True" | config.benchmarks]
          ]
          ++ concat
            [ "" : stanza p ("ghc-options: " <> config.ghcOptions)
            | not (T.null config.ghcOptions)
            , p <- project.packages
            ]

    parallelScript :: [Package] -> T.Text
    parallelScript pkgs =
      heredoc . L.intercalate [""] $ [stanza p ("ghc-options: -j" <> tshow config.jobs) | p <- pkgs]

    stanza :: Package -> T.Text -> [T.Text]
    stanza p line = ["package " <> T.pack p.name, "  " <> line]

    heredoc :: [T.Text] -> T.Text
    heredoc ls = T.unlines $ ["cat >> cabal.project.local <<'EOF'"] ++ ls ++ ["EOF"]

    -- The entries without the GHC job semaphore, grouped by their packages.
    parallelGroups :: [([GhcEntry], [Package])]
    parallelGroups =
      [ ([e.ghc | e <- oldEntries, names e.packages == names pkgs], pkgs)
      | pkgs <- L.nubBy (\a b -> names a == names b) (map (.packages) oldEntries)
      ]
      where
        oldEntries :: [MatrixEntry]
        oldEntries = [e | e <- project.matrix, not (hasSemaphore e.ghc)]

        names :: [Package] -> [String]
        names = map (.name)

    semaphoreEntries :: [GhcEntry]
    semaphoreEntries = filter hasSemaphore entries

    -- The semaphore needs GHC 9.8. A matrix entry is an exact version or a
    -- major series, so the range decides each entry completely.
    hasSemaphore :: GhcEntry -> Bool
    hasSemaphore e = decide (orLaterVersion (mkVersion [9, 8])) e == Included

    testEntries :: [GhcEntry]
    testEntries = [e.ghc | e <- project.matrix, any (.hasTestSuite) e.packages]

    cacheRestore :: Node
    cacheRestore =
      mapping
        [ ("uses", plain "actions/cache/restore@v6")
        , ("id", plain "cache")
        ,
          ( "with"
          , mapping
              [ ("path", plain "${{ steps.setup.outputs.cabal-store }}")
              , ("key", plain $ "${{ runner.os }}-ghc-${{ steps.setup.outputs.ghc-version }}-${{ hashFiles('" <> planJson <> "') }}")
              , ("restore-keys", plain "${{ runner.os }}-ghc-${{ steps.setup.outputs.ghc-version }}-")
              ]
          )
        ]

    planJson :: T.Text
    planJson = T.pack $ if projectDir == "." then "dist-newstyle/cache/plan.json" else projectDir </> "dist-newstyle/cache/plan.json"

    cacheSave :: Node
    cacheSave =
      mapping
        [ ("uses", plain "actions/cache/save@v6")
        , ("if", plain "steps.cache.outputs.cache-hit != 'true'")
        ,
          ( "with"
          , mapping
              [ ("path", plain "${{ steps.setup.outputs.cabal-store }}")
              , ("key", plain "${{ steps.cache.outputs.cache-primary-key }}")
              ]
          )
        ]

    aptScript :: [T.Text] -> T.Text
    aptScript packages =
      T.unlines
        [ "sudo apt-get update"
        , "sudo apt-get install -y --no-install-recommends " <> T.unwords (map shellQuote packages)
        ]

    shellQuote :: T.Text -> T.Text
    shellQuote t = "'" <> T.replace "'" "'\\''" t <> "'"

    tshow :: Int -> T.Text
    tshow = T.pack . show
