{-# LANGUAGE OverloadedStrings #-}

-- The lists of the workflow join their parts with concat, also if there are
-- only two parts.
{- HLINT ignore "Use ++" -}

-- | The generated workflow.
module HaskellGha.Workflow
  ( -- * Workflow
    generate
  , workflow
  , renderWorkflow
  , findWorkflows
  ) where

import Control.Monad
import Control.Monad.Trans.Except
import Data.Bifunctor
import Data.ByteString qualified as BS
import Data.Char
import Data.Either
import Data.Foldable
import Data.Functor
import Data.List qualified as L
import Data.Maybe
import Data.Text qualified as T
import Data.Text.Encoding qualified as T
import Distribution.Pretty
import Distribution.Version
import System.Directory
import System.FilePath

import HaskellGha.Check
import HaskellGha.Config
import HaskellGha.Ghc
import HaskellGha.Options
import HaskellGha.Project
import HaskellGha.Yaml

-- | Read the configuration and the project, and make the workflow. The phases
-- run in order, and each phase shows all its errors.
generate
  :: FilePath
  -- ^ The root of the repository. The paths of the options are relative to it.
  -> Options
  -> IO (Either [String] Node)
generate root opts = runExceptT $ do
  (config, source) <- ExceptT $ readConfig root opts.config
  project <- ExceptT $ readProject root opts.projectDir
  except $ workflow opts source config project

-- | Render the workflow with its header comment.
renderWorkflow
  :: String
  -- ^ The version of the tool.
  -> Options
  -> Node
  -> T.Text
renderWorkflow version opts =
  renderDocument
    [ headerMarker
    , "  " <> T.unwords (map (shellQuote . T.pack) $ commandLine opts)
    , ""
    , "To regenerate it, run from the root of the repository:"
    , "  haskell-gha"
    , ""
    , "Version: " <> T.pack version
    , ""
    , "For more information, see https://github.com/arybczak/haskell-gha"
    ]
    separated
  where
    separated :: [T.Text] -> Bool
    separated = \case
      [] -> True
      ["jobs"] -> True
      ["jobs", _, "steps"] -> True
      _ -> False

-- | The first line of the header. The next line has the command.
headerMarker :: T.Text
headerMarker = "Do not edit this file, it was generated by the following command:"

-- | The options of each workflow that the tool generated, from the command in
-- its header. The output of the command must be the file itself.
findWorkflows
  :: FilePath
  -- ^ The root of the repository.
  -> IO (Either [String] [Options])
findWorkflows root = do
  exists <- doesDirectoryExist (root </> dir)
  names <- if exists then L.sort . filter ((`elem` [".yml", ".yaml"]) . takeExtension) <$> listDirectory (root </> dir) else pure []
  results <- forM names $ \name -> recorded (dir </> name) . T.lines . T.decodeUtf8Lenient <$> BS.readFile (root </> dir </> name)
  pure $ case partitionEithers results of
    ([], found) -> case catMaybes found of
      [] -> Left ["No workflow in " ++ dir ++ " was generated by haskell-gha. To make one, run haskell-gha --generate."]
      workflows -> Right workflows
    (errors, _) -> Left errors
  where
    dir :: FilePath
    dir = takeDirectory defaultOptions.output

    recorded :: FilePath -> [T.Text] -> Either String (Maybe Options)
    recorded path = \case
      marker : command : _ | commentText marker == Just headerMarker -> first ((path ++ ": ") ++) $ do
        args <- maybe (Left "the command in the header has a quote without its end") Right $ shellWords . T.unpack =<< commentText command
        opts <- first ("the command in the header is not valid: " ++) (parseCommandLine args)
        if normalise opts.output == normalise path
          then Right (Just opts)
          else Left $ "the command in the header writes the workflow to " ++ opts.output ++ ", not to this file"
      _ -> Right Nothing

    commentText :: T.Text -> Maybe T.Text
    commentText = fmap T.strip . T.stripPrefix "#"

    -- The words of a command line from 'shellQuote'.
    shellWords :: String -> Maybe [String]
    shellWords s = case dropWhile (== ' ') s of
      "" -> Just []
      s' -> do
        (w, rest) <- shellWord s'
        (w :) <$> shellWords rest

    shellWord :: String -> Maybe (String, String)
    shellWord = \case
      '\'' : rest -> case break (== '\'') rest of
        (quoted, _ : rest') -> first (quoted ++) <$> shellWord rest'
        (_, []) -> Nothing
      '\\' : c : rest -> first (c :) <$> shellWord rest
      c : rest | c /= ' ' -> first (c :) <$> shellWord rest
      rest -> Just ("", rest)

-- | A step of the build job, or the comment lines after a hook.
data StepItem
  = Step Node
  | Lines [Line]

-- | Quote a word for bash, if it needs quotes.
shellQuote :: T.Text -> T.Text
shellQuote t
  | not (T.null t) && T.all (\c -> isAsciiLower c || isAsciiUpper c || isDigit c || c `elem` ("-_./=:+@%," :: String)) t = t
  | otherwise = "'" <> T.replace "'" "'\\''" t <> "'"

-- | Make the workflow.
workflow :: Options -> ConfigSource -> Config -> Project -> Either [String] Node
workflow opts source config project = runCheck $ checks $> root
  where
    entries :: [GhcEntry]
    entries = map (.ghc) project.matrix

    checks :: Check ()
    checks = do
      traverse_ checkGhcValue (matrixValues ["include", "exclude"] "ghc" config)
      checkDependencies
      when config.doctest.enabled $ do
        traverse_ (checkDoctestRange config.doctest.ghc) entries
        traverse_ checkSkip config.doctest.skip
      traverse_ checkImport project.imports
      when config.sdist $
        traverse_ checkInside project.packages
      when config.hlint.enabled $
        traverse_ checkHLintPath config.hlint.path

    -- An error at a value of the configuration, with its position.
    failureAt :: Offset -> String -> Check ()
    failureAt off msg = traverse_ failure (sourceErrors source [(off, msg)])

    -- The action gets the path on the runner, where only the repository
    -- exists.
    checkHLintPath :: Located HLintPath -> Check ()
    checkHLintPath p
      | isAbsolute path || leadsAbove (projectDir </> path) =
          failureAt p.offset $
            "the path "
              ++ path
              ++ " is not in the repository. Give a path relative to the project directory."
      | otherwise = pure ()
      where
        path :: FilePath
        path = T.unpack p.value.value

    -- cabal fetches an import from a URL. It reads a local file on the runner,
    -- where only the repository exists, and the copy of the source tarballs
    -- does not contain it.
    checkImport :: Import -> Check ()
    checkImport i
      | "://" `L.isInfixOf` i.target = pure ()
      | isAbsolute i.target || leadsAbove (projectDir </> i.target) =
          failure $
            i.location
              ++ "the imported file "
              ++ i.target
              ++ " is not in the repository. Give a path relative to the project directory."
      | config.sdist =
          failure $
            i.location
              ++ "the workflow builds the source tarballs in a copy of the project directory, and the copy does not contain the imported file "
              ++ i.target
              ++ ". Set sdist: false in the configuration."
      | otherwise = pure ()

    -- The unpack step keeps the path of each package relative to the project
    -- directory, so a path with .. leads out of the copy.
    checkInside :: Package -> Check ()
    checkInside p
      | leadsAbove p.directory =
          failure $
            "Package "
              ++ p.name
              ++ " is in "
              ++ p.directory
              ++ ", outside the project directory, but the workflow builds the source tarballs in a copy of the project directory. Set sdist: false in the configuration."
      | otherwise = pure ()

    checkDoctestRange :: Located VersionRange -> GhcEntry -> Check ()
    checkDoctestRange r = either (failureAt r.offset) (const (pure ())) . decideRange ("the range " ++ prettyShow r.value) r.value

    checkSkip :: Located T.Text -> Check ()
    checkSkip p
      | T.unpack p.value `elem` map (.name) project.packages = pure ()
      | otherwise = failureAt p.offset $ "the project has no local package " ++ T.unpack p.value

    -- The tool makes the dependencies axis only for both. Otherwise the name
    -- is free for an axis of the user.
    checkDependencies :: Check ()
    checkDependencies
      | bothDependencies = do
          traverse_ ownAxis [key.offset | (key@Node {content = Scalar _ "dependencies"}, _) <- matrixEntries config]
          traverse_ value (matrixValues ["include", "exclude"] "dependencies" config)
      | "dependencies" `elem` matrixAxes config = pure ()
      | otherwise = traverse_ noAxis (matrixValues ["exclude"] "dependencies" config)
      where
        ownAxis :: Offset -> Check ()
        ownAxis off = failureAt off "the tool makes the dependencies axis for dependencies: both, so the matrix must not contain it"

        value :: Located T.Text -> Check ()
        value v
          | v.value `elem` ["newest", "oldest"] = pure ()
          | otherwise = failureAt v.offset $ "dependencies " ++ T.unpack v.value ++ " is not in the dependencies axis, which contains only newest, oldest"

        noAxis :: Located T.Text -> Check ()
        noAxis v = failureAt v.offset "the matrix has no dependencies axis. Set dependencies: both to add it."

    checkGhcValue :: Located T.Text -> Check ()
    checkGhcValue v
      | v.value `elem` map entryText entries = pure ()
      | otherwise =
          failureAt v.offset $
            "GHC "
              ++ T.unpack v.value
              ++ " is not in the ghc axis, which contains only "
              ++ L.intercalate ", " (map (T.unpack . entryText) entries)

    root :: Node
    root =
      mapping
        [ "name" .= copied config.name
        , -- GitHub reads a plain on as a string. The encoder quotes it,
          -- because YAML 1.1 reads it as a boolean.
          (plain "on", triggers)
        , "permissions" .= copied config.permissions
        , -- A push to a branch of the push trigger also cancels the older
          -- run. The newer run tests the newer code and saves the cache that
          -- the older run did not save.
          "concurrency"
            .= mapping
              [ "group" .= plain "${{ github.workflow }}-${{ github.ref }}"
              , "cancel-in-progress" .= True
              ]
        , "defaults"
            .= mapping
              [ "run"
                  .= mappingConcat
                    [ ["shell" .= plain "bash"]
                    , workingDirectory
                    ]
              ]
        , -- The short jobs come first, so the long build job does not hide
          -- them.
          "jobs"
            .= mappingConcat
              [ ["fourmolu" .= fourmoluJob config.fourmolu | config.fourmolu.enabled]
              , ["hlint" .= hlintJob config.hlint | config.hlint.enabled]
              , ["build" .= job]
              ]
        ]

    mappingConcat :: [[(Node, Node)]] -> Node
    mappingConcat = mapping . concat

    -- The workflow has its own layout, so the empty lines above a copied
    -- entry are left out.
    copied :: Commented a -> Commented a
    copied c = Commented c.value c.comments {before = filter (/= EmptyLine) c.comments.before}

    triggers :: Node
    triggers =
      mapping
        [ "push" .= mapping ["branches" .= copied config.branches]
        , "pull_request" .= nullValue
        , "merge_group" .= nullValue
        , "workflow_dispatch" .= nullValue
        ]

    workingDirectory :: [(Node, Node)]
    workingDirectory = ["working-directory" .= plain (T.pack projectDir) | projectDir /= "."]

    projectDir :: FilePath
    projectDir = dropTrailingPathSeparator (normalise opts.projectDir)

    job :: Node
    job =
      mappingConcat
        [
          [ "name" .= jobName
          , runsOn
          ]
        , ["container" .= plain c.image | Just c <- [config.container]]
        , [timeout]
        , ["services" .= copied s | Just s <- [config.services]]
        ,
          [ "strategy"
              .= mapping
                [ "fail-fast" .= False
                , "matrix" .= copied (Commented matrix config.matrix.comments)
                ]
          ]
        , ["steps" .= steps]
        ]

    runsOn :: (Node, Node)
    runsOn = "runs-on" .= copied config.runsOn

    timeout :: (Node, Node)
    timeout = "timeout-minutes" .= config.timeoutMinutes.value

    -- The job needs no GHC, so it runs once, next to the build jobs.
    fourmoluJob :: Fourmolu -> Node
    fourmoluJob f =
      mapping
        [ "name" .= plain "Fourmolu"
        , runsOn
        , timeout
        , "steps"
            .= sequenceNode
              [ checkoutStep NoSubmodules
              , mapping
                  [ uses "haskell-actions/run-fourmolu" "" config.actions.runFourmolu
                  , "with"
                      .= mappingConcat
                        [ ["version" .= singleQuoted (T.pack (prettyShow f.version))]
                        , ["pattern" .= literal (T.unlines (map (.value) f.patterns)) | not (null f.patterns)]
                        , -- The run defaults do not apply to an action.
                          workingDirectory
                        ]
                  ]
              ]
        ]

    hlintJob :: HLint -> Node
    hlintJob h =
      mapping
        [ "name" .= plain "HLint"
        , runsOn
        , timeout
        , "steps"
            .= sequenceNode
              [ checkoutStep NoSubmodules
              , mapping
                  [ uses "haskell-actions/hlint-setup" "" config.actions.hlintSetup
                  , "with" .= mapping ["version" .= singleQuoted (T.pack (prettyShow h.version))]
                  ]
              , mapping
                  [ uses "haskell-actions/hlint-run" "" config.actions.hlintRun
                  , "with"
                      .= mappingConcat
                        [ ["path" .= p | Just p <- [hlintPath h]]
                        , ["fail-on" .= h.failOn]
                        ]
                  ]
              ]
        ]

    -- The action runs in the root of the repository and takes one path, or a
    -- JSON array of paths. Without a path, it checks the root.
    hlintPath :: HLint -> Maybe Node
    hlintPath h = case paths of
      ["."] -> Nothing
      [p] -> Just (singleQuoted (T.pack p))
      ps -> Just (singleQuoted ("[" <> T.intercalate ", " (map (jsonString . T.pack) ps) <> "]"))
      where
        paths :: [FilePath]
        paths
          | null h.path = [projectDir]
          | otherwise = [dropTrailingPathSeparator (normalise (projectDir </> T.unpack p.value.value)) | p <- h.path]

        jsonString :: T.Text -> T.Text
        jsonString t = "\"" <> T.concatMap (\c -> if c `elem` ['"', '\\'] then T.pack ['\\', c] else T.singleton c) t <> "\""

    -- The fourmolu and HLint jobs do not fetch the submodules, because the
    -- files of a submodule are not the code of the project.
    checkoutStep :: Submodules -> Node
    checkoutStep submodules =
      mapping $
        uses "actions/checkout" "" config.actions.checkout : case submodules of
          NoSubmodules -> []
          TopSubmodules -> ["with" .= mapping ["submodules" .= True]]
          RecursiveSubmodules -> ["with" .= mapping ["submodules" .= plain "recursive"]]

    -- The default repository, and the path of the action in the repository,
    -- e.g. /restore.
    uses :: T.Text -> T.Text -> ActionRef -> (Node, Node)
    uses repo path a = "uses" .= plain (fromMaybe repo a.repository <> path <> "@" <> a.ref)

    jobName :: Node
    jobName = case parts of
      [p] -> plain p
      ps -> singleQuoted (T.intercalate ", " ps)
      where
        -- The values newest and oldest are clear without the axis name.
        parts :: [T.Text]
        parts =
          concat
            [ ["GHC ${{ matrix.ghc }}"]
            , ["${{ matrix.dependencies }}" | bothDependencies]
            , [a <> " ${{ matrix." <> a <> " }}" | a <- matrixAxes config]
            ]

    bothDependencies :: Bool
    bothDependencies = config.dependencies == DependenciesBoth

    -- The comments after the matrix are in its entry, so the entry writes
    -- them after the new matrix.
    matrix :: Node
    matrix =
      mappingConcat
        [ ["ghc" .= sequenceNode (map (singleQuoted . entryText) entries)]
        , ["dependencies" .= sequenceNode [plain "newest", plain "oldest"] | bothDependencies]
        , extraAxes
        ]

    -- The lines of the matrix itself, i.e. the lines above an empty line
    -- before its first entry, go above that entry, not above the ghc axis.
    -- The empty lines there are dropped, because the ghc axis now comes
    -- before them.
    extraAxes :: [(Node, Node)]
    extraAxes = case matrixEntries config of
      (k, v) : rest -> (dropEmptyLines (addBefore config.matrix.value.value.comments.before k), v) : rest
      [] -> []
      where
        dropEmptyLines :: Node -> Node
        dropEmptyLines n = Node n.offset n.endOffset n.props n.comments {before = filter (/= EmptyLine) n.comments.before} n.content

    -- A hook can install a library that the build plan needs, and the
    -- tarballs can contain a file that a hook makes.
    steps :: Node
    steps =
      placeLines $
        concat
          [ map Step setupSteps
          , hookItems setupHook
          , map Step buildSteps
          , hookItems buildHook
          , map Step testSteps
          ]

    setupHook, buildHook :: Hook
    (setupHook, buildHook) = placedHooks config.hooks

    hookItems :: Hook -> [StepItem]
    hookItems h = map Step h.steps ++ [Lines h.trailing | not (null h.trailing)]

    -- The comment lines after a hook go before the next step, and an empty
    -- line separates them from that step. If no step follows, they go after
    -- the last step.
    placeLines :: [StepItem] -> Node
    placeLines items = addAfter end (sequenceNode nodes)
      where
        nodes :: [Node]
        end :: [Line]
        (nodes, end) = foldr place ([], []) items

        place :: StepItem -> ([Node], [Line]) -> ([Node], [Line])
        place item (ns, ls) = case (item, ns) of
          (Step n, _) -> (n : ns, ls)
          (Lines hookLines, n : rest) -> (addBefore (hookLines ++ [EmptyLine]) n : rest, ls)
          (Lines hookLines, []) -> ([], hookLines ++ ls)

    setupSteps :: [Node]
    setupSteps =
      concat
        [ [checkoutStep config.submodules]
        , [runStep "Install the system packages" Nothing (aptScript config.apt) | not (null config.apt)]
        , [runStep "Install the gold linker" (Just goldEntries) (aptScript ["binutils-gold"]) | not (null goldEntries)]
        , [setupStep]
        , [versionsStep]
        ]

    buildSteps :: [Node]
    buildSteps =
      concat
        [ [ runStep "Unpack the source tarballs" (Just group) (unpackScript pkgs)
          | config.sdist
          , (group, pkgs) <- packageGroups project.matrix
          ]
        , [sourceStep "Configure the project" Nothing configureScript]
        , oldestStep
        , [ sourceStep "Enable parallel module builds for the local packages" (Just group) (parallelScript pkgs)
          | (group, pkgs) <- packageGroups [e | e <- project.matrix, not (hasSemaphore e.ghc)]
          ]
        , [ sourceStep "Enable the GHC job semaphore" (Just semaphoreEntries) "echo 'semaphore: True' >> cabal.project.local\n"
          | not (null semaphoreEntries)
          ]
        , [planStep]
        , [cacheRestore]
        , [sourceStep "Build the dependencies" Nothing "cabal build all --only-dependencies\n"]
        , [cacheSave]
        , concat [doctestSteps config.doctest | not (null doctestEntries)]
        , [sourceStep "Build" Nothing "cabal build all\n"]
        ]

    testSteps :: [Node]
    testSteps =
      concat
        [ [ sourceStep "Run the tests" (Just testEntries) "cabal test all --test-show-details=direct\n"
          | config.tests
          , not (null testEntries)
          ]
        , [ sourceStep ("Run doctest for " <> T.pack p.name) (Just es) (doctestScript config.doctest p)
          | p <- project.packages
          , T.pack p.name `notElem` map (.value) config.doctest.skip
          , not (null p.doctestArgs)
          , let es = [e.ghc | e <- project.matrix, e.ghc `elem` doctestEntries, p.directory `elem` map (.directory) e.packages]
          , not (null es)
          ]
        , [ sourceStep "Check the packages" (Just group) (checkScript pkgs)
          | config.check
          , (group, pkgs) <- packageGroups project.matrix
          ]
        , [ sourceStep "Build the documentation" Nothing "cabal haddock all --disable-documentation --haddock-all --haddock-for-hackage\n"
          | config.haddock
          ]
        ]

    -- The entries in the range of doctest.ghc. The workflow installs doctest
    -- for such an entry also if no package runs it there, e.g. if doctest.skip
    -- names all packages. Only an unusual configuration does that, so the tool
    -- accepts the extra steps.
    doctestEntries :: [GhcEntry]
    doctestEntries
      | config.doctest.enabled = [e | e <- entries, decide config.doctest.ghc.value e == Included]
      | otherwise = []

    -- The key of the main cache does not depend on the doctest version, so
    -- doctest has its own cache with only the binary.
    doctestSteps :: Doctest -> [Node]
    doctestSteps d =
      [ mappingConcat
          [
            [ "name" .= plain "Find the doctest version"
            , "id" .= plain "doctest"
            ]
          , doctestIf []
          , ["run" .= literal findDoctest]
          ]
      , mappingConcat
          [
            [ uses "actions/cache" "/restore" config.actions.cache
            , "id" .= plain "doctest-cache"
            ]
          , doctestIf []
          ,
            [ "with"
                .= mapping
                  [ "path" .= plain "~/.local/bin/doctest"
                  , "key" .= plain "${{ runner.os }}-${{ steps.versions.outputs.image }}-doctest-${{ steps.doctest.outputs.version }}-ghc-${{ steps.setup.outputs.ghc-version }}"
                  ]
            ]
          ]
      , mappingConcat
          [ ["name" .= plain "Install doctest"]
          , doctestIf [cacheMiss]
          , ["run" .= literal "cabal install doctest --ignore-project --install-method=copy --installdir=\"$HOME/.local/bin\" --overwrite-policy=always --constraint='doctest ==${{ steps.doctest.outputs.version }}'\n"]
          ]
      , -- A separate save step keeps the binary also if a later step fails.
        mappingConcat
          [ [uses "actions/cache" "/save" config.actions.cache]
          , doctestIf [cacheMiss]
          ,
            [ "with"
                .= mapping
                  [ "path" .= plain "~/.local/bin/doctest"
                  , "key" .= plain "${{ steps.doctest-cache.outputs.cache-primary-key }}"
                  ]
            ]
          ]
      ]
      where
        cacheMiss :: T.Text
        cacheMiss = "steps.doctest-cache.outputs.cache-hit != 'true'"

        doctestIf :: [T.Text] -> [(Node, Node)]
        doctestIf extra = case [condition doctestEntries | doctestEntries /= entries] ++ extra of
          [] -> []
          cs -> ["if" .= plain (T.intercalate " && " cs)]

        -- A store that already contains doctest gives a plan without it, so the
        -- dry run uses an empty store.
        findDoctest :: T.Text
        findDoctest =
          T.unlines
            [ "version=$(cabal --store-dir=\"$RUNNER_TEMP\"/doctest-store install doctest --ignore-project --dry-run"
                <> maybe "" (\r -> " --constraint=" <> shellQuote ("doctest " <> T.pack (prettyShow r))) d.version
                <> " | sed -n 's/^ - doctest-\\([0-9.]*\\) (exe:doctest).*/\\1/p')"
            , "if [ -z \"$version\" ]; then"
            , "  echo 'The dry run of cabal install shows no doctest version.' >&2"
            , "  exit 1"
            , "fi"
            , "echo \"version=$version\" >> \"$GITHUB_OUTPUT\""
            ]

    doctestScript :: Doctest -> Package -> T.Text
    doctestScript d p =
      T.unlines $
        ["cd " <> shellQuote (T.pack p.directory) | p.directory /= "."]
          ++ [T.unwords ("\"$HOME\"/.local/bin/doctest" : map shellQuote (d.options ++ map T.pack args)) | args <- p.doctestArgs]

    -- cabal check works on the package in the current directory, and its
    -- output does not name the package. The step runs with bash -e, so a
    -- failed check must not end the script before the other packages.
    checkScript :: [Package] -> T.Text
    checkScript pkgs =
      T.unlines $
        concat
          [
            [ "failed=0"
            , "check() {"
            , "  echo \"Checking the package $1\""
            , "  (cd \"$2\" && cabal check) || { echo \"::error::cabal check failed for the package $1\"; failed=1; }"
            , "}"
            ]
          , ["check " <> shellQuote (T.pack p.name) <> " " <> shellQuote (T.pack p.directory) | p <- pkgs]
          , ["exit \"$failed\""]
          ]

    -- The content of the tarballs, at the same relative paths as in the project
    -- directory.
    sourceDir :: T.Text
    sourceDir = "\"$RUNNER_TEMP\"/haskell-gha"

    -- The step makes the tarballs of the packages of the matrix entry, so a
    -- package that is not in the project has no tarball. The pattern of a
    -- tarball allows only a version after the name, because the tarball of a
    -- package foo-2d also starts with foo-.
    unpackScript :: [Package] -> T.Text
    unpackScript pkgs =
      T.unlines $
        [ "shopt -s extglob"
        , "cabal sdist all --output-directory=\"$RUNNER_TEMP\"/haskell-gha-sdist"
        , "mkdir " <> sourceDir
        , "for f in cabal.project cabal.project.freeze cabal.project.local; do"
        , "  if [ -f \"$f\" ]; then cp \"$f\" " <> sourceDir <> "; fi"
        , "done"
        ]
          ++ concat
            [ ["mkdir -p " <> dir | p.directory /= "."]
                ++ ["tar -xzf \"$RUNNER_TEMP\"/haskell-gha-sdist/" <> T.pack p.name <> "-+([0-9.]).tar.gz --strip-components=1 -C " <> dir]
            | p <- pkgs
            , let dir = if p.directory == "." then sourceDir else sourceDir <> "/" <> shellQuote (T.pack p.directory)
            ]

    -- A step with a script. The script runs for the given matrix entries, or
    -- for all of them.
    runStep :: T.Text -> Maybe [GhcEntry] -> T.Text -> Node
    runStep = step False

    -- A step that runs in the content of the tarballs, if sdist is true.
    sourceStep :: T.Text -> Maybe [GhcEntry] -> T.Text -> Node
    sourceStep = step config.sdist

    step :: Bool -> T.Text -> Maybe [GhcEntry] -> T.Text -> Node
    step inSource name only script =
      mappingConcat
        [ ["name" .= plain name]
        , ["if" .= plain (condition es) | Just es <- [only], es /= entries]
        , [sourceWorkingDirectory | inSource]
        , ["run" .= literal script]
        ]

    sourceWorkingDirectory :: (Node, Node)
    sourceWorkingDirectory = "working-directory" .= plain "${{ runner.temp }}/haskell-gha"

    -- hashFiles only reads files in the workspace, and the content of the
    -- tarballs is outside it. Thus the step gives the hash of the plan to the
    -- cache key as an output.
    planStep :: Node
    planStep =
      mappingConcat
        [
          [ "name" .= plain "Make the build plan"
          , "id" .= plain "plan"
          ]
        , [sourceWorkingDirectory | config.sdist]
        ,
          [ "run"
              .= literal
                ( T.unlines
                    [ "cabal build all --dry-run"
                    , "echo \"hash=$(sha256sum dist-newstyle/cache/plan.json | cut -d ' ' -f 1)\" >> \"$GITHUB_OUTPUT\""
                    ]
                )
          ]
        ]

    condition :: [GhcEntry] -> T.Text
    condition es =
      "contains(fromJSON('[" <> T.intercalate "," ["\"" <> entryText e <> "\"" | e <- es] <> "]'), matrix.ghc)"

    setupStep :: Node
    setupStep =
      mapping
        [ uses "haskell-actions/setup" "" config.actions.setup
        , "id" .= plain "setup"
        , "with"
            .= mapping
              [ "ghc-version" .= plain "${{ matrix.ghc }}"
              , "cabal-version" .= singleQuoted cabalVersion
              ]
        ]

    cabalVersion :: T.Text
    cabalVersion = case config.cabalVersion of
      CabalLatest -> "latest"
      CabalVersion v -> T.pack (prettyShow v)

    -- An expression cannot read the environment variable ImageOS of the runner,
    -- so the step gives it to the cache key as an output. In a container, the
    -- variable is empty, and the image of the container takes its place.
    versionsStep :: Node
    versionsStep =
      mapping
        [ "name" .= plain "Show the versions"
        , "id" .= plain "versions"
        , "run"
            .= literal
              ( T.unlines
                  [ "ghc --version"
                  , "cabal --version"
                  , "echo \"GHC ${{ steps.setup.outputs.ghc-version }}, cabal ${{ steps.setup.outputs.cabal-version }}, image " <> summaryImage <> "\" >> \"$GITHUB_STEP_SUMMARY\""
                  , "echo \"image=" <> keyImage <> "\" >> \"$GITHUB_OUTPUT\""
                  ]
              )
        ]
      where
        summaryImage, keyImage :: T.Text
        (summaryImage, keyImage) = case config.container of
          Nothing -> ("$ImageOS $ImageVersion", "$ImageOS")
          Just c -> (c.image, c.image)
    configureScript :: T.Text
    configureScript =
      heredoc $
        concat
          [ ["jobs: " <> tshow config.jobs.value]
          , ["tests: True" | config.tests]
          , ["benchmarks: True" | config.benchmarks]
          , ["write-ghc-environment-files: always" | not (null doctestEntries)]
          , concat
              [ "" : stanza p ("ghc-options: " <> config.ghcOptions.value)
              | not (T.null config.ghcOptions.value)
              , p <- project.packages
              ]
          , case T.lines (T.dropWhileEnd isSpace config.cabalProjectLocal.value) of
              [] -> []
              ls -> "" : ls
          ]

    -- Each later cabal command reads cabal.project.local, so all of them use
    -- the plan with the oldest versions.
    oldestStep :: [Node]
    oldestStep = case config.dependencies of
      DependenciesNewest -> []
      DependenciesOldest -> [preferOldest []]
      DependenciesBoth -> [preferOldest ["if" .= plain "matrix.dependencies == 'oldest'"]]
      where
        preferOldest :: [(Node, Node)] -> Node
        preferOldest only =
          mappingConcat
            [ ["name" .= plain "Prefer the oldest dependencies"]
            , only
            , [sourceWorkingDirectory | config.sdist]
            , ["run" .= literal "echo 'prefer-oldest: True' >> cabal.project.local\n"]
            ]

    parallelScript :: [Package] -> T.Text
    parallelScript pkgs =
      heredoc . L.intercalate [""] $ [stanza p ("ghc-options: -j" <> tshow config.jobs.value) | p <- pkgs]

    stanza :: Package -> T.Text -> [T.Text]
    stanza p line = ["package " <> T.pack p.name, "  " <> line]

    heredoc :: [T.Text] -> T.Text
    heredoc ls = T.unlines $ ["cat >> cabal.project.local <<'EOF'"] ++ ls ++ ["EOF"]

    -- The matrix entries, grouped by their packages.
    packageGroups :: [MatrixEntry] -> [([GhcEntry], [Package])]
    packageGroups es =
      [ ([e.ghc | e <- es, names e.packages == names pkgs], pkgs)
      | pkgs <- L.nubBy (\a b -> names a == names b) (map (.packages) es)
      ]
      where
        names :: [Package] -> [String]
        names = map (.name)

    semaphoreEntries :: [GhcEntry]
    semaphoreEntries = filter hasSemaphore entries

    -- The semaphore needs GHC 9.8. A matrix entry is an exact version or a
    -- major series, so the range decides each entry completely.
    hasSemaphore :: GhcEntry -> Bool
    hasSemaphore e = decide (orLaterVersion (mkVersion [9, 8])) e == Included

    -- The hsc2hs of GHC 9.4 and older links with gold also if the runner has
    -- no gold, and Ubuntu 25.10 and later do not install gold by default.
    goldEntries :: [GhcEntry]
    goldEntries = [e | e <- entries, decide (earlierVersion (mkVersion [9, 5])) e == Included]

    testEntries :: [GhcEntry]
    testEntries = [e.ghc | e <- project.matrix, any (.hasTestSuite) e.packages]

    cacheRestore :: Node
    cacheRestore =
      mapping
        [ uses "actions/cache" "/restore" config.actions.cache
        , "id" .= plain "cache"
        , "with"
            .= mapping
              [ "path" .= plain "${{ steps.setup.outputs.cabal-store }}"
              , "key" .= plain (cachePrefix <> "${{ steps.plan.outputs.hash }}")
              , "restore-keys" .= plain cachePrefix
              ]
        ]

    -- A store from another image can link against system libraries that this
    -- image does not have. The prefix is also the restore key, so a job
    -- restores only a store with its own kind of dependencies.
    cachePrefix :: T.Text
    cachePrefix =
      "${{ runner.os }}-${{ steps.versions.outputs.image }}-ghc-${{ steps.setup.outputs.ghc-version }}-" <> case config.dependencies of
        DependenciesNewest -> ""
        DependenciesOldest -> "oldest-"
        DependenciesBoth -> "${{ matrix.dependencies }}-"

    cacheSave :: Node
    cacheSave =
      mapping
        [ uses "actions/cache" "/save" config.actions.cache
        , "if" .= plain "steps.cache.outputs.cache-hit != 'true'"
        , "with"
            .= mapping
              [ "path" .= plain "${{ steps.setup.outputs.cabal-store }}"
              , "key" .= plain "${{ steps.cache.outputs.cache-primary-key }}"
              ]
        ]

    -- A job in a container runs as root, and the image has no sudo.
    aptScript :: [T.Text] -> T.Text
    aptScript packages =
      T.unlines
        [ sudo <> "apt-get update"
        , sudo <> "apt-get install -y --no-install-recommends " <> T.unwords (map shellQuote packages)
        ]
      where
        sudo :: T.Text
        sudo = maybe "sudo " (const "") config.container

    tshow :: Int -> T.Text
    tshow = T.pack . show
