cabal-version: 3.0
name:          a
version:       0
tested-with:   GHC == 9.6.7 || ^>= { 9.10, 9.12 }

library
  hs-source-dirs:     src
  exposed-modules:    A
  default-language:   GHC2021
  default-extensions: LambdaCase
                      OverloadedStrings

library internal
  hs-source-dirs:   internal
  exposed-modules:  A.Internal
  default-language: Haskell2010
